<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <UserSecretsId>88a44644-82c7-4f1e-b4dd-5ce9dcbdf871</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.MobileServer.Web\Template.MobileServer.Web.csproj" />
  </ItemGroup>

</Project>
