<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>0d8f8f34-d568-4e0e-a352-e110c487090b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.MobileServer.Web\Template.MobileServer.Web.csproj" />
  </ItemGroup>

</Project>
