<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Template.MobileServer</RootNamespace>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    <PackageReference Include="Usa.Smart.Core" Version="2.5.0" />
    <PackageReference Include="Usa.Smart.Data.Accessor.Core" Version="2.10.0" />
    <PackageReference Include="Usa.Smart.Data.Accessor.Extensions.DependencyInjection" Version="2.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Core\" />
    <Folder Include="Domain\Enum\" />
    <Folder Include="Domain\Logic\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Usa.Smart.Analyzers.JapaneseComment" Version="1.4.0" />
  </ItemGroup>

</Project>
